# Generated by Django 5.0.4 on 2024-04-07 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('img', models.ImageField(null=True, upload_to='product_imgs/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productcategory')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.seller')),
            ],
        ),
    ]
